name: docker install
description: 'Install Docker'
inputs:
  REMOTE_USER:
    description: 'Remote Server User'
    required: true
  SERVER_IP:
    description: 'Remote Server IP'
    required: true
runs: 
  using: 'composite'
  steps:
    - name: Install Docker
      shell: bash
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa_uptime ${{ inputs.REMOTE_USER }}@${{ inputs.SERVER_IP }} << 'EOF'
        if ! [ -x "$(command -v docker)" ]; then
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          if ! groups $USER | grep &>/dev/null '\bdocker\b'; then
            sudo usermod -aG docker $USER
          fi
          if ! sudo systemctl is-active --quiet docker; then
            sudo systemctl restart docker
          fi
        fi
        EOF

    - name: Install OpenTelemetry Collector Contrib
      shell: bash
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa_uptime ${{ inputs.REMOTE_USER }}@${{ inputs.SERVER_IP }} << 'EOF'
        if ! [ -x "$(command -v otelcol-contrib)" ]; then
          sudo apt update -qq
          sudo apt install -y wget
          wget https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.121.0/otelcol-contrib_0.121.0_linux_amd64.deb
          sudo dpkg -i otelcol-contrib_0.121.0_linux_amd64.deb
          if ! sudo systemctl is-active --quiet otelcol-contrib; then
          sudo systemctl restart otelcol-contrib
          fi
        fi
        EOF

    - name: Install Nginx
      shell: bash
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa_uptime ${{ inputs.REMOTE_USER }}@${{ inputs.SERVER_IP }} << 'EOF'
        if ! [ -x "$(command -v nginx)" ]; then
          sudo apt update -qq
          sudo apt install -y nginx
          if ! sudo systemctl is-active --quiet nginx; then
            sudo systemctl restart nginx
          fi
        fi
        EOF

    - name: Install HAProxy
      shell: bash
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa_uptime ${{ inputs.REMOTE_USER }}@${{ inputs.SERVER_IP }} << 'EOF'
        if ! [ -x "$(command -v haproxy)" ]; then
          sudo apt update -qq
          sudo apt install -y haproxy
          if ! sudo systemctl is-active --quiet haproxy; then
            sudo systemctl restart haproxy
          fi
        fi
        if ! [ -x "$(command -v socat)" ]; then
          sudo apt update -qq
          sudo apt install -y socat
        fi
        EOF