name: Staging Deploy

on:
    push:
        # branches:
        #     - develop

jobs:
    deploy:
        runs-on: self-hosted

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Docker build
          uses: docker/build-push-action@v6
          with:
            context: ./docker/prod/server.Dockerfile
            push: false
            tags: uptime-backend:develop