name: Staging deploy

on:
  push:
    branches: ["develop"]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.set-image-name.outputs.image_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name as output
        id: set-image-name
        run: echo "image_name=ghcr.io/bluewave-labs/checkmate-backend:staging" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/bluewave-labs/checkmate-backend:staging \
            -f ./docker/staging/server.Dockerfile \
            --label org.opencontainers.image.source=https://github.com/bluewave-labs/checkmate-backend \
            .

  push-to-ghcr:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GHCR
        run: docker push ${{ needs.docker-build.outputs.image_name }}

  deploy-to-staging:
    needs: push-to-ghcr
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server and restart container using Docker Compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGING_SERVER_HOST }}
          username: ${{ secrets.STAGING_SERVER_USER }}
          key: ${{ secrets.STAGING_SERVER_SSH_KEY }}
          script: |
            cd /checkmate/server/docker/staging
            docker-compose down
            docker-compose pull
            docker-compose up -d
